# Generated by Django 4.2.1 on 2023-05-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='iddocente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='idmaestrante',
            field=models.IntegerField(null=True),
        ),
    ]
