# Generated by Django 4.2.1 on 2023-05-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
