# Generated by Django 3.2 on 2023-02-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_documento', models.CharField(max_length=200, verbose_name='Título')),
                ('archivo_documento', models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('estado_documento', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created'],
            },
        ),
    ]
