# Generated by Django 3.2.4 on 2023-04-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='aut_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
