# Generated by Django 4.1 on 2023-04-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_documento_aut_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProcesoTesis',
            fields=[
                ('id_procesos_tesis', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_documento', models.CharField(max_length=200, verbose_name='Título')),
                ('archivo_documento', models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/procesotesis/')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha almacenado')),
                ('estado_documento', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
