# Generated by Django 4.1 on 2023-04-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_documentoprocesotesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoprocesotesis',
            name='archivo_documento',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/'),
        ),
    ]
