# Generated by Django 4.1 on 2023-04-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_alter_documentoprocesotesis_archivo_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoprocesotesis',
            options={'ordering': ['-fecha_creado'], 'verbose_name': 'Documento Proceso Tesis', 'verbose_name_plural': 'Documentos Procesos Tesis'},
        ),
        migrations.AlterField(
            model_name='documentoprocesotesis',
            name='archivo_documento',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='tesis/procesotesis/'),
        ),
    ]
