# Generated by Django 4.1 on 2023-04-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_alter_documentoprocesotesis_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoprocesotesis',
            old_name='id_procesos_tesis',
            new_name='id_procesotesis',
        ),
    ]
