# Generated by Django 4.2.1 on 2023-05-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_rename_id_procesos_tesis_documentoprocesotesis_id_procesotesis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoProcesoTesis',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='aut_documento',
        ),
    ]
