# Generated by Django 4.2.1 on 2023-09-20 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documento", "0007_delete_documentoprocesotesis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="archivo_documento",
            field=models.FileField(
                blank=True,
                max_length=254,
                null=True,
                upload_to="tesis/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
