# Generated by Django 4.2.1 on 2023-09-03 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maestrante",
            name="nueva_version",
        ),
        migrations.RemoveField(
            model_name="maestrante",
            name="programa_regular",
        ),
        migrations.RemoveField(
            model_name="maestrante",
            name="reincorporacion",
        ),
        migrations.RemoveField(
            model_name="maestrante",
            name="version_cursada",
        ),
        migrations.RemoveField(
            model_name="maestrante",
            name="vigencia_final",
        ),
        migrations.RemoveField(
            model_name="maestrante",
            name="vigencia_inicio",
        ),
        migrations.RemoveField(
            model_name="maestrante",
            name="vigencia_matricula",
        ),
    ]
