# Generated by Django 4.2.1 on 2024-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cod_notificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rol',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(blank=True, choices=[(1, 'Maestrante'), (2, 'Docente'), (3, 'Técnico  de Postgrado/Coordinación de investigación'), (5, 'Coordinación de Postgrado')], null=True),
        ),
    ]
