# Generated by Django 4.2.1 on 2023-09-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0002_remove_maestrante_nueva_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maestrante",
            name="nueva_version",
            field=models.CharField(
                blank=True, max_length=220, null=True, verbose_name="Nueva versión"
            ),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="programa_regular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="reincorporacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="version_cursada",
            field=models.CharField(
                blank=True, max_length=220, null=True, verbose_name="Versión cursada"
            ),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="vigencia_final",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="vigencia_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="vigencia_matricula",
            field=models.BooleanField(default=False),
        ),
    ]
