# Generated by Django 4.2.1 on 2024-01-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_tribunaltesis_tribunal_tesis_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunaltesis',
            name='tribunal_tesis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.docente'),
        ),
    ]
