# Generated by Django 4.2.1 on 2024-05-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_banconotificacion_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='banconotificacion',
            name='enviar',
            field=models.BooleanField(default=True),
        ),
    ]
