# Generated by Django 4.2.1 on 2023-09-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "usuario",
            "0003_maestrante_nueva_version_maestrante_programa_regular_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma",
            name="fecha_4",
            field=models.DateField(blank=True, null=True),
        ),
    ]
