# Generated by Django 4.2.1 on 2024-01-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_sustentaciontesishistorial_dictamen_escala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroactividades',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
