# Generated by Django 4.2.1 on 2024-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_banconotificacion_enviar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avancehistorial',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='informeguiaformulario',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='informerevisor',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reportegeneral',
            name='docente2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
