# Generated by Django 4.2.1 on 2023-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0004_cronograma_fecha_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma2",
            name="fecha_borrador_prorroga",
            field=models.DateField(blank=True, null=True),
        ),
    ]
