# Generated by Django 4.2.1 on 2024-05-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_avance_docente_avance_2_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='docente',
        ),
    ]
