# Generated by Django 4.2.1 on 2024-02-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_centroactividades_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma2',
            name='fecha_reporte_general_tribunal_interno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='otras_obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='informeguia',
            name='otras_obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
