# Generated by Django 4.2.1 on 2024-02-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_cronograma2_fecha_reporte_general_tribunal_interno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='bibliografia',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='cap4',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='cap5',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='sug',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='biblioragia',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='cap1',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='cap2',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='cap3',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='avance_2',
            name='sug',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='biblioragia',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='cap1',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='cap2',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='cap3',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='avance_2_histoiral',
            name='sug',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='bibliografia',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='cap4',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='cap5',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='avancehistorial',
            name='sug',
        ),
        migrations.AddField(
            model_name='avance',
            name='cap1_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance',
            name='cap2_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance',
            name='cap3_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='cap4_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='cap5_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='cap6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capitulo VI'),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='cap6_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='cap7',
            field=models.IntegerField(blank=True, null=True, verbose_name='REFERENCIAS'),
        ),
        migrations.AddField(
            model_name='avance_2',
            name='cap7_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='cap4_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='cap5_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='cap6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capitulo VI'),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='cap6_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='cap7',
            field=models.IntegerField(blank=True, null=True, verbose_name='REFERENCIAS'),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='cap7_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avancehistorial',
            name='cap1_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avancehistorial',
            name='cap2_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='avancehistorial',
            name='cap3_cualitativo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='avance_2',
            name='cap4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capitulo IV'),
        ),
        migrations.AlterField(
            model_name='avance_2',
            name='cap5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capitulo V'),
        ),
        migrations.AlterField(
            model_name='avance_2_histoiral',
            name='cap4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capitulo IV'),
        ),
        migrations.AlterField(
            model_name='avance_2_histoiral',
            name='cap5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capitulo V'),
        ),
    ]
