# Generated by Django 4.2.1 on 2024-05-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_avance_2_histoiral_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informeguiaformulario',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='informerevisor',
            name='docente',
        ),
        migrations.AddField(
            model_name='informe',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='informeguia',
            name='docente',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
