# Generated by Django 4.2.1 on 2024-05-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_informeguiaformulario_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestrante',
            name='procedencia_tesis',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
