# Generated by Django 4.2.1 on 2024-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_maestrante_procedencia_tesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoConfigurar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Correo')),
                ('host_password', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Contraseña')),
            ],
        ),
    ]
