# Generated by Django 4.2.1 on 2024-02-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_avancehistorial_fecha_programada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancehistorial',
            name='fecha_programada',
        ),
    ]
