# Generated by Django 4.2.1 on 2023-09-19 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0008_alter_avance_2_histoiral_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maestrante",
            name="fecha_nombramiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maestrante",
            name="nombramiento_revisor",
            field=models.FileField(
                blank=True,
                max_length=254,
                null=True,
                upload_to="tesis/nombramiento_revisor/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
