# Generated by Django 4.2.1 on 2024-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_avancehistorial_fecha_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancehistorial',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
