# Generated by Django 4.2.1 on 2023-09-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0009_maestrante_fecha_nombramiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma2",
            name="fecha_formulario_guia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cronograma2",
            name="fecha_formulario_revisor",
            field=models.DateField(blank=True, null=True),
        ),
    ]
