# Generated by Django 4.2.1 on 2024-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_correoconfigurar'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoconfigurar',
            name='identificacion_correo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
