# Generated by Django 4.2.1 on 2024-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_correoconfigurar_identificacion_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoconfigurar',
            name='puerto_correo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
