# Generated by Django 4.2.1 on 2024-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_avancehistorial_fecha_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancehistorial',
            name='docete_guia',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
