# Generated by Django 4.2.1 on 2023-09-20 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0010_cronograma2_fecha_formulario_guia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informerevisor",
            name="obs",
        ),
        migrations.RemoveField(
            model_name="informerevisor",
            name="pagina",
        ),
    ]
