# Generated by Django 4.2.1 on 2024-02-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_avancehistorial_docete_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='docete_guia',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='avance_2_histoiral',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
