# Generated by Django 4.2.1 on 2024-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_correoconfigurar_puerto_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correoconfigurar',
            options={'verbose_name': 'Correo', 'verbose_name_plural': 'Correos'},
        ),
        migrations.AddField(
            model_name='sustentaciontesishistorial',
            name='instancia',
            field=models.IntegerField(null=True),
        ),
    ]
