# Generated by Django 4.2.1 on 2023-09-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0012_rename_usuario_activo_usuario_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cambio_password",
            field=models.BooleanField(default=False),
        ),
    ]
