# Generated by Django 4.2.1 on 2023-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0013_usuario_cambio_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="centroactividades",
            name="archivo_documento",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="tesis/actividades/"
            ),
        ),
    ]
