# Generated by Django 4.2.1 on 2024-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_rename_fecha_asistenciainduccion_fecha_realizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='reunion_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
