# Generated by Django 4.2.1 on 2023-10-01 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0014_centroactividades_archivo_documento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maestrante",
            name="form_habilitacion",
        ),
    ]
