# Generated by Django 4.2.1 on 2024-02-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_alter_asistenciainduccion_fecha_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciainduccion',
            name='enlace_reunion',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
