# Generated by Django 4.2.1 on 2024-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_asistenciainduccion_hoja_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroactividades',
            name='numero_actividad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
