# Generated by Django 3.2 on 2023-02-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
