# Generated by Django 4.2.1 on 2024-02-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alter_notification_text_alter_notification_verbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verbo',
            field=models.CharField(max_length=800),
        ),
    ]
