# Generated by Django 4.2.1 on 2024-03-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_notification_maestrante_notification_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tipo_notificacion',
        ),
    ]
