# Generated by Django 4.2.1 on 2024-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_remove_notification_tipo_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cod_notificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='rol',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
